#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-msm
Version  : 1.8
Release  : 49
URL      : https://cran.r-project.org/src/contrib/msm_1.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/msm_1.8.tar.gz
Summary  : Multi-State Markov and Hidden Markov Models in Continuous Time
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-msm-lib = %{version}-%{release}
Requires: R-expm
Requires: R-generics
Requires: R-mvtnorm
Requires: R-tibble
BuildRequires : R-expm
BuildRequires : R-generics
BuildRequires : R-mvtnorm
BuildRequires : R-tibble
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Markov multi-state models to longitudinal data.  Designed for
    processes observed at arbitrary times in continuous time (panel data)
    but some other observation schemes are supported. Both Markov
    transition rates and the hidden Markov output process can be modelled
    in terms of covariates, which may be constant or piecewise-constant
    in time.

%package lib
Summary: lib components for the R-msm package.
Group: Libraries

%description lib
lib components for the R-msm package.


%prep
%setup -q -n msm
pushd ..
cp -a msm buildavx2
popd
pushd ..
cp -a msm buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725781880

%install
export SOURCE_DATE_EPOCH=1725781880
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/msm/CITATION
/usr/lib64/R/library/msm/DESCRIPTION
/usr/lib64/R/library/msm/INDEX
/usr/lib64/R/library/msm/Meta/Rd.rds
/usr/lib64/R/library/msm/Meta/data.rds
/usr/lib64/R/library/msm/Meta/features.rds
/usr/lib64/R/library/msm/Meta/hsearch.rds
/usr/lib64/R/library/msm/Meta/links.rds
/usr/lib64/R/library/msm/Meta/nsInfo.rds
/usr/lib64/R/library/msm/Meta/package.rds
/usr/lib64/R/library/msm/Meta/vignette.rds
/usr/lib64/R/library/msm/NAMESPACE
/usr/lib64/R/library/msm/NEWS
/usr/lib64/R/library/msm/NEWS.md
/usr/lib64/R/library/msm/R/msm
/usr/lib64/R/library/msm/R/msm.rdb
/usr/lib64/R/library/msm/R/msm.rdx
/usr/lib64/R/library/msm/data/Rdata.rdb
/usr/lib64/R/library/msm/data/Rdata.rds
/usr/lib64/R/library/msm/data/Rdata.rdx
/usr/lib64/R/library/msm/doc/index.html
/usr/lib64/R/library/msm/doc/msm-manual.R
/usr/lib64/R/library/msm/doc/msm-manual.Rnw
/usr/lib64/R/library/msm/doc/msm-manual.pdf
/usr/lib64/R/library/msm/help/AnIndex
/usr/lib64/R/library/msm/help/aliases.rds
/usr/lib64/R/library/msm/help/msm.rdb
/usr/lib64/R/library/msm/help/msm.rdx
/usr/lib64/R/library/msm/help/paths.rds
/usr/lib64/R/library/msm/html/00Index.html
/usr/lib64/R/library/msm/html/R.css
/usr/lib64/R/library/msm/tests/test_base.R
/usr/lib64/R/library/msm/tests/testthat/helper.r
/usr/lib64/R/library/msm/tests/testthat/test_analyticp.r
/usr/lib64/R/library/msm/tests/testthat/test_boot.R
/usr/lib64/R/library/msm/tests/testthat/test_datasumm.r
/usr/lib64/R/library/msm/tests/testthat/test_deriv.r
/usr/lib64/R/library/msm/tests/testthat/test_draic.r
/usr/lib64/R/library/msm/tests/testthat/test_hmodel2list.R
/usr/lib64/R/library/msm/tests/testthat/test_models.r
/usr/lib64/R/library/msm/tests/testthat/test_models_hmm.r
/usr/lib64/R/library/msm/tests/testthat/test_models_hmmmulti.r
/usr/lib64/R/library/msm/tests/testthat/test_models_misc.r
/usr/lib64/R/library/msm/tests/testthat/test_msm2Surv.R
/usr/lib64/R/library/msm/tests/testthat/test_pearson.R
/usr/lib64/R/library/msm/tests/testthat/test_phase.R
/usr/lib64/R/library/msm/tests/testthat/test_ppass.R
/usr/lib64/R/library/msm/tests/testthat/test_simul.R
/usr/lib64/R/library/msm/tests/testthat/test_tidy.R
/usr/lib64/R/library/msm/tests/testthat/test_utils.r
/usr/lib64/R/library/msm/tests/testthat/test_viterbi.R
/usr/lib64/R/library/msm/tests/testthat/test_weights.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/msm/libs/msm.so
/V4/usr/lib64/R/library/msm/libs/msm.so
/usr/lib64/R/library/msm/libs/msm.so
